### PR TITLE
64 - Updated composer to version 1.4.2.

### LINKED ISSUE #64: Update composer to the latest version
Latest is 1.4.2 https://github.com/composer/composer/releases

### PR DESCRIPTION
**Pull request by aleksijohansson**
Fixes #64.

### CODE REVIEW

**Comment by aleksijohansson** [comment]
Not tested locally so waiting for test builds to pass.

**Review by james-nesbitt — APPROVED** [review]
this is needed, and approved.

I had forgotten about this version pinning and will focus on this more in future updates.

**Comment by james-nesbitt** [comment]
I am not sure about the travis run.  it looks like it skipped the docker build?

**Comment by aleksijohansson** [comment]
@james-nesbitt There is a small arrow on the left hand side where you can collapse the docker build output.

**Pull request merged**
