### PR TITLE
Added global Composer installation.

### PR DESCRIPTION
**Pull request by aleksijohansson**

### CODE REVIEW

**Comment by aleksijohansson** [comment]
This should cover #2

**Comment by james-nesbitt** [comment]
developershell-buildfail
https://quay.io/repository/wunder/wundertools-image-fuzzy-developershell/build/4a5a0d2d-730e-496f-b68a-6dc9e24237a6

build fails in quay.io.  Something to do with openssl.

Interestingly, I switched the php_copy() for a curl, and still get the same issue when the composer installer runs.

@aleksijohansson @operinko do you guys have quay.io accounts yet?

**Comment by james-nesbitt** [comment]
@aleksijohansson can you please add "php7-openssl" to the list of php7 packages

**Comment by james-nesbitt** [comment]
latest changes (added php7-openssl) seemed to fix the build:

https://quay.io/repository/wunder/wundertools-image-fuzzy-developershell/build/795df216-d3f9-4483-9dba-dd7623196046

**Comment by operinko** [comment]
@james-nesbitt I do have a quay.io account (ollierinko).

**Pull request merged**
